services:
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    restart: unless-stopped
    env_file:
      - ../.env

    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}

    volumes:
      - /srv/apps/radarr:/config
      - /srv/media:/srv/media

    ports:
      - "7878:7878"

    networks:
      - homelab

networks:
  homelab:
    external: true
