name: homepage-stack

services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    ports:
      - '3000:3000'
    volumes:
      - ./config:/app/config
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - HOMEPAGE_ALLOWED_HOSTS=*
    networks:
      - homelab
    restart: always

  glances:
    image: nicolargo/glances:latest-full
    container_name: glances
    pid: host
    environment:
      - GLANCES_OPT=-w --refresh 2 -C /etc/glances/glances.conf --host-proc /host/proc
    ports:
      - '61208:61208'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /sys:/sys:ro
      - /proc:/host/proc:ro
      - ./glances.conf:/etc/glances/glances.conf:ro
    networks:
      - homelab
    restart: always

networks:
  homelab:
    external: true
