services:
  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin
    env_file:
      - ../.env

    restart: unless-stopped

    ports:
      - "8096:8096"

    devices:
      - /dev/dri:/dev/dri

    volumes:
      - ./config:/config
      - ./cache:/cache
      - /srv/media:/media

    environment:
      TZ: ${TZ}

    networks:
      - homelab

networks:
  homelab:
    external: true
